# -*- coding: utf-8 -*-
import json

CATS = [
    ("roupas_rn", "Roupas RN"),
    ("roupas_p", "Roupas P (0-3 meses)"),
    ("roupas_m", "Roupas M (3-6 meses)"),
    ("roupas_g", "Roupas G (6-9 meses)"),
    ("roupas_gg", "Roupas GG (9-12 meses)"),
    ("roupas_geral", "Roupas - uso geral"),
    ("quarto", "Quarto"),
    ("banho", "Higiene e banho"),
    ("eletronicos", "Eletronicos"),
    ("alimentacao", "Alimentacao"),
    ("farmacia", "Farmacia"),
    ("passeio", "Passeio e transporte"),
    ("adicionais", "Itens adicionais"),
]
CAT_ALIASES = {
    "roupas_rn": r"roupas?.*\brn\b",
    "roupas_p": r"roupas?.*(\bp\b|0-3)",
    "roupas_m": r"roupas?.*(\bm\b(?!eses|\w)|3-6)",
    "roupas_g": r"roupas?.*(\bg\b(?!g)|6-9)",
    "roupas_gg": r"roupas?.*(\bgg\b|9-12)",
    "roupas_geral": r"roupas?.*(geral|uso geral)",
    "quarto": r"quarto",
    "banho": r"higiene|banho",
    "eletronicos": r"eletr",
    "alimentacao": r"aliment",
    "farmacia": r"farmac",
    "passeio": r"passeio|transporte",
    "adicionais": r"adicional",
}

def it(cat, name, qty, size="", note="", source=None):
    return {"cat": cat, "name": name, "qty": qty, "size": size, "note": note, "source": source}

ITEMS = []

ITEMS += [
    it("roupas_rn", "Body manga curta", 4, "RN", "Clima de Salvador: priorize manga curta (Carter's)"),
    it("roupas_rn", "Body manga longa", 4, "RN", "Para ar-condicionado e noites; levar 2 para a maternidade"),
    it("roupas_rn", "Roupa de sair", 2, "RN", "As que vao para a mala da maternidade"),
    it("roupas_rn", "Saida de maternidade", 2, "RN", "Roupa maternidade azul marinho completa com manta + saida bege"),
    it("roupas_rn", "Meias", 1, "RN", "1 pacote"),
    it("roupas_rn", "Sapatinho", 1, "RN", "Sapato quase nao e usado nessa fase"),
    it("roupas_rn", "Luvas", 1, "RN", "Evita arranhoes no rosto"),
    it("quarto", "Enxoval de berco", 4, "", "Levar 2 jogos para a maternidade"),
    it("quarto", "Saco de dormir", 1, "RN", ""),

    it("roupas_p", "Body manga curta", 6, "P", "Carter's"),
    it("roupas_p", "Body manga longa", 4, "P", "Macacao de ima, hello word, polo, girafa, body manga longa"),
    it("roupas_p", "Roupa de sair", 2, "P", "Short e blusa bege de ursinho"),
    it("roupas_p", "Meias", 1, "P", "1 pacote"),
    it("roupas_p", "Sapatos", 1, "P", ""),

    it("roupas_m", "Body manga curta", 7, "M", "2 body de cachorrinho, body do Flamengo"),
    it("roupas_m", "Body manga longa", 3, "M", "Body de ursinho Trousseau"),
    it("roupas_m", "Roupa de sair", 3, "M", "Body de linha com sapatinho"),
    it("roupas_m", "Meias", 1, "M", "1 pacote"),
    it("roupas_m", "Sapatos", 2, "M", ""),

    it("roupas_g", "Body manga curta", 6, "G", "Carter's"),
    it("roupas_g", "Body manga longa", 2, "G", ""),
    it("roupas_g", "Roupa de sair", 4, "G", ""),
    it("roupas_g", "Meias", 1, "G", "1 pacote"),
    it("roupas_g", "Sapatos", 2, "G", ""),
    it("roupas_g", "Roupa UV piscina/praia", 1, "G", ""),

    it("roupas_gg", "Body manga curta", 5, "GG", "Body de barquinho"),
    it("roupas_gg", "Body manga longa", 2, "GG", ""),
    it("roupas_gg", "Roupa de sair", 4, "GG", ""),
    it("roupas_gg", "Meias", 1, "GG", "1 pacote"),
    it("roupas_gg", "Sapatos", 1, "GG", ""),
    it("roupas_gg", "Roupa UV piscina/praia", 1, "GG", ""),

    it("roupas_geral", "Pano de boca", 15, "", "Recomendacao geral: 12-20 unidades; parte pode ser presente"),
    it("roupas_geral", "Manta/Cueiro", 4, "", "Tecidos leves para o clima de Salvador"),
    it("roupas_geral", "Casaquinho", 2, "", "Mesmo em clima quente: maternidade e ambientes com ar-condicionado"),
    it("banho", "Toalha de banho com capuz", 3, "", "So falta 1 (prefira uma atoalhada maior; ja tem estilo fralda)"),
    it("banho", "Fraldao de banho", 5, "", ""),
    it("banho", "Fraldas descartaveis", 4, "RN e P", "RN usa 8-10 fraldas/dia (~700-900 em 3 meses). Nao estocar demais o RN; testar a marca antes de comprar volume"),
    it("banho", "Banheira com suporte", 1, "", "", "brasil"),
    it("banho", "Termometro de banho", 1, "", ""),
    it("banho", "Kit manicure e higiene (cortador de unha, pente, escova)", 1, "", ""),
    it("banho", "Perfume baby", 1, "", ""),
    it("quarto", "Ninho redutor de berco", 1, "", "Yoggi (marca brasileira). Atencao: usar apenas com supervisao - nao recomendado para sono sem vigilancia"),
    it("quarto", "Naninha", 1, "", ""),
    it("quarto", "Cesto/saco para roupa suja do bebe", 1, "", "Opcional, ajuda na organizacao"),
    it("quarto", "Cabide de veludo", 1, "", "1 kit"),
    it("quarto", "Kit berco/lencois", 3, "", ""),
    it("quarto", "Tapete de atividades", 1, "", "", "brasil"),
    it("quarto", "Livro de contraste", 1, "", "Usado ate os 3 meses"),

    it("adicionais", "Mala da maternidade", 1, "", "Deixar pronta entre a 32a e 35a semana"),
    it("adicionais", "Bolsa de passeio grande", 1, "", "Para o dia a dia / hospital"),
    it("adicionais", "Mochila de passeio", 1, "", "Opcional; facilita saidas rapidas. Ver modelo Fjallraven"),
    it("adicionais", "Bolsa maternidade pequena", 1, "", "Opcional, facilita saidas rapidas"),
    it("adicionais", "Lixo de fralda anti-odor", 1, "", "", "brasil"),
    it("adicionais", "Boia de piscina", 1, "", ""),
    it("adicionais", "Almofada de amamentacao", 1, "", "Comprada na Quatro Estacoes; avaliar se precisa de uma segunda"),
    it("adicionais", "Travesseiro de amamentacao (Boppy)", 1, "", "Tambem serve de apoio para o bebe sentar mais tarde"),
    it("adicionais", "Sutia de amamentacao", 4, "", "Amiga sugere comprar no Brasil, mas ha opcoes em MacroBaby/Target nos EUA"),
    it("adicionais", "Rosquinha de amamentacao", 4, "", "", "brasil"),
    it("adicionais", "Mordedor", 2, "", ""),
    it("adicionais", "Chocalho", 2, "", ""),
    it("adicionais", "Girafa (brinquedo)", 1, "", "Sophie la Girafe"),

    it("eletronicos", "Baba eletronica", 1, "", "V-Tech"),
    it("eletronicos", "Ruido branco", 1, "", ""),
    it("eletronicos", "Nebulizador", 1, "", "Gtech"),
    it("eletronicos", "Bomba de amamentacao", 1, "", "Medela, Elvie ou Momcozy - pesquisar antes"),
    it("eletronicos", "Aspirador nasal", 1, "", "Frida (~US$ 39,99)"),
    it("eletronicos", "Maquina de lavar/secar/esterilizar mamadeira", 1, "", "Ou so o esterilizador + suporte de secar"),

    it("alimentacao", "Esterilizador", 1, "", "Avent (~US$ 85)"),
    it("alimentacao", "Mamadeira", 4, "", "2 ja compradas (Avent 0-3M); comprar mais 2 + bicos. Nao comprar mamadeira de 130ml"),
    it("alimentacao", "Aquecedor de mamadeira", 1, "", "Avent (~US$ 35 - mais barato que Walmart/Amazon)"),
    it("alimentacao", "Chupeta", 2, "", "Bebe tem preferencia de bico - testar Avent e MAM antes de estocar"),
    it("alimentacao", "Porta bico", 2, "", ""),
    it("alimentacao", "Porta chupeta", 1, "", "O que vem na bolsa de passeio"),
    it("alimentacao", "Prendedor de chupeta", 1, "", ""),
    it("alimentacao", "Copos de transicao", 2, "", "Munchkin / Comotomo / snack catcher"),
    it("alimentacao", "Babador de silicone", 3, "", ""),
    it("alimentacao", "Babador bandana", 6, "", "Algodao (~US$ 2 cada)"),
    it("alimentacao", "Colher de refeicao", 6, "", "Bambu (2 kits); extra: colher Skip Hop"),
    it("alimentacao", "Prato com ventosa", 3, "", "Mushie / bambu"),
    it("alimentacao", "Bowl", 2, "", ""),
    it("alimentacao", "Garrafa termica", 2, "", "Thermos"),
    it("alimentacao", "Pote termico", 2, "", "Thermos"),
    it("alimentacao", "Escorredor de mamadeira", 1, "", "Considerado \"importantissimo\" pela amiga"),
    it("alimentacao", "Potinho com tampa", 2, "", ""),
    it("alimentacao", "Copinho snack catcher", 1, "", ""),
    it("alimentacao", "Cadeira de alimentacao", 1, "", "Uso a partir de ~6 meses (Graco, Ingenuity nos EUA)"),

    it("farmacia", "Colic Calm", 2, "", "Embalagem azul - melhor preco: Amazon (US$ 17)"),
    it("farmacia", "Culturelle Baby", 2, "", "Bem mais caro no Brasil - Amazon (US$ 16,26)"),
    it("farmacia", "A+D Prevent grande (pote)", 1, "", "Amazon (US$ 14,47)"),
    it("farmacia", "A+D Prevent pequeno (bisnaga)", 5, "", "Amazon (US$ 4,63)"),
    it("farmacia", "Desitin roxa", 2, "", "Amazon (US$ 7)"),
    it("farmacia", "Palmer's Butter", 1, "", "Para gravidez/estrias"),
    it("farmacia", "Garmastan", 1, "", "Pomada para o bico do peito (produto brasileiro)", "brasil"),
    it("farmacia", "Compressa de silicone para febre", 1, "", "Amiga tambem cotou BeKoool (3 und) e adesivo indicador de febre"),
    it("farmacia", "Fita para medir alcool no leite", 1, "", ""),
    it("farmacia", "Saco para armazenar leite", 1, "", "", "brasil"),
    it("farmacia", "Protetor solar de bebe", 2, "", "Baby Ganics - stick e spray"),
    it("farmacia", "Repelente aerosol spray", 1, "", "Baby Ganics (~US$ 12)"),
    it("farmacia", "Caneta para picada de inseto", 1, "", "After Bite / BiteMD (US$ 5,99)"),
    it("farmacia", "Adesivo repelente de mosquito", 1, "", "Scentpellent (US$ 4,99)"),
    it("farmacia", "Sabonete baby", 4, "", "Cetaphil ou Mustela (~US$ 8)"),
    it("farmacia", "Shampoo baby", 4, "", "Cetaphil ou Mustela (~US$ 8)"),
    it("farmacia", "Escova + pente baby", 1, "", "Primo Passi (US$ 5,99)"),
    it("farmacia", "Termometro baby", 1, "", "~US$ 14"),
    it("farmacia", "Lenco umedecido para catarro", 5, "", "Frida (US$ 4,99)"),
    it("farmacia", "Lenco umedecido de agua", 2, "", "WaterWipes 240 (US$ 14,27-14,98)"),
    it("farmacia", "Pasta de dente natural", 2, "", "Dr. Brown's (US$ 4,49)"),
    it("farmacia", "Escova de dente baby", 2, "", "MAM (~US$ 4)"),
    it("farmacia", "Escova de dente treinamento", 1, "", "Ali+Oli Koala (US$ 12,99)"),
    it("farmacia", "Oleo essencial", 1, "", "Frida"),
    it("farmacia", "Absorvente para seios", 1, "", "Comprar o modelo HARD"),
    it("farmacia", "Aparelho repelente de mosquito", 1, "", "Primo Passi"),
    it("farmacia", "Compressa termica para mama", 1, "", "Kushies"),

    it("passeio", "Carrinho de bebe", 1, "", "Modelo Nuna Trvl Rx"),
    it("passeio", "Cadeirinha multietapas / bebe conforto", 1, "", "Sistema que serve como bebe conforto e cadeirinha de carro"),
    it("passeio", "Espelho para banco traseiro", 1, "", "Brica 360, Munchkin ou Skip Hop (~US$ 19,99)"),
    it("passeio", "Prendedor de sacola para carrinho", 2, "", "The Mommy Hook - comprar 2"),
    it("passeio", "Mosquiteiro para carrinho", 1, "", "Cor preta"),
    it("passeio", "Canguru", 1, "", ""),
]

TIPS = {
    "nao_vale": [
        "Protetor de silicone para bico dos seios (Medela)",
        "Pomada Lansinoh",
        "Porta-fruta de chupar (Mochi)",
        "Mamadeira de 130 ml",
    ],
    "extras_valem": [
        "Mosquiteiro para carrinho (cor preta)",
        "Absorvente para seios - modelo HARD",
        "Rodelinhas - comprar na Shopee (Brasil)",
        "Sutia de amamentacao - MacroBaby ou Target (2 a 4 und)",
        "Saquinho para armazenar leite",
        "Gancho de compras para carrinho - comprar 2",
        "Espelho para carro - Skip Hop",
        "Potinho com tampa",
        "Colher da Skip Hop",
        "Copinho snack catcher",
        "Escorredor para mamadeira - considerado importantissimo",
    ],
    "onde_comprar": [
        "Comprar no Brasil: sutia de amamentacao (opcao), rosquinha de amamentacao, saco para armazenar leite, Garmastan, rodelinhas (Shopee)",
        "Nos EUA: MacroBaby, Walmart, Amazon - a Amazon costuma ter o melhor preco na farmacia",
        "Outlets em Miami: Dolphin Mall e Sawgrass Mills",
    ],
    "orcamento": "Referencia da amiga: Farmacia ~US$ 360 | Alimentacao/itens uteis ~US$ 469 (sem roupas, eletronicos e carrinho)",
}

def pc(desc, qty, size, note, link_cat=None, link_name=None):
    return {"desc": desc, "qty": qty, "size": size, "note": note, "link": ([link_cat, link_name] if link_cat else None)}

PIECES = [
    pc("Toalha de banho com capuz", 2, "", "", "banho", "Toalha de banho com capuz"),
    pc("Cueiro com pelinhos", 1, "", "", "roupas_geral", "Manta/Cueiro"),
    pc("Cueiro em algodao", 1, "", "", "roupas_geral", "Manta/Cueiro"),
    pc("Sapatinho All Star", 1, "RN", "", "roupas_rn", "Sapatinho"),
    pc("Mamadeira Avent", 2, "0-3M", "", "alimentacao", "Mamadeira"),
    pc("Escova limpadora de mamadeira Avent", 1, "", "", None, None),
    pc("Conjunto short e body sem manga", 1, "3-6M", "", "roupas_m", "Roupa de sair"),
    pc("Body com manga", 1, "0-3M", "", "roupas_p", "Body manga longa"),
    pc("Macaquinho sem manga", 1, "3-6M", "", "roupas_m", "Roupa de sair"),
    pc("Macaquinho sem manga", 1, "3-6M", "", "roupas_m", "Roupa de sair"),
    pc("Macaquinho sem manga", 1, "9-12M", "", "roupas_gg", "Roupa de sair"),
    pc("Conjunto short e blusa", 1, "3M", "", "roupas_p", "Roupa de sair"),
    pc("Pano de boca", 1, "", "", "roupas_geral", "Pano de boca"),
    pc("Pano de boca", 1, "", "", "roupas_geral", "Pano de boca"),
    pc("Conjunto calca com pezinho, touca e blusa manga longa", 1, "0-3M", "", "roupas_p", "Roupa de sair"),
    pc("Conjuntinho tricot (body + sapatinho)", 1, "3-6M", "", "roupas_m", "Roupa de sair"),
    pc("Projetor de estrelas", 1, "", "", None, None),
    pc("Meias", 1, "0-3M", "Registrado na planilha como 7 pares", "roupas_p", "Meias"),
    pc("Naninha", 1, "", "", "quarto", "Naninha"),
    pc("Conjunto body manga longa, calca com pezinho, cueiro e touca", 1, "3M", "", "roupas_p", "Body manga longa"),
    pc("Conjunto body manga longa, calca com pezinho e touca", 1, "3M", "", "roupas_p", "Body manga longa"),
    pc("Body manga longa + calca com pezinho", 1, "M", "", "roupas_m", "Body manga longa"),
    pc("Body manga longa + calca com pezinho", 1, "0-3M", "", "roupas_p", "Body manga longa"),
    pc("Body manga longa + calca", 1, "3M", "", "roupas_p", "Roupa de sair"),
]

out = {
    "cats": [{"key": k, "label": v, "alias": CAT_ALIASES[k]} for k, v in CATS],
    "items": ITEMS,
    "pieces": PIECES,
    "tips": TIPS,
}
with open("seed.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
print("items:", len(ITEMS), "pieces:", len(PIECES))
